version: '2.4'

services:
  demo:
    image: demo/app:1.0.0
    build:
      context: ../
      dockerfile: docker/demo/Dockerfile
      args:
        - "JAR_PATH=build/libs/demo-0.0.1-SNAPSHOT.jar"
    environment:
      - "JAR_NAME=demo-0.0.1-SNAPSHOT.jar"
      - "JVM_OPTIONS="
      - "ELASTIC_APM_SERVICE_NAME=user-service"
      - "ELASTIC_APM_APPLICATION_PACKAGES=com.example.demo"
      - "ELASTIC_APM_SERVER_URLS=http://apm:8200"
      - "MYSQL_HOST=mysql"
      - "MYSQL_DATABASE=users"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=ecvbjkl9876t"
    ports:
      - 8080:8080
    links:
      - apm
      - mysql

  kibana:
    image: kibana:7.4.0
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  apm:
    image: elastic/apm-server:7.4.0
    build:
      context: elastic-apm
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qazxsw
      MYSQL_DATABASE: users
      MYSQL_USER: app
      MYSQL_PASSWORD: ecvbjkl9876t
