apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-apm-demo
  labels:
    app: elastic-apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-apm-demo
  template:
    metadata:
      labels:
        app: elastic-apm-demo
    spec:
      containers:
      - name: elastic-apm-demo
        image: tomqwu/voter-service:api
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: SPRING_PROFILE
          value: poc
        - name: MONGODB_HOST
          value: localhost
        - name: ELASTIC_APM_ACTIVE
          value: "true"
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          value: "org.example,org.example"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "service-user"
        - name: ELASTIC_APM_SERVER_URLS
          value: "https://apm-server-quickstart-apm-http:8200/"
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: "false"
        - name: ELASTIC_APM_SECRET_TOKEN
          value: "c92cq56gnjmkrr44vb566qwh"
      - name: voter-service-nginx-api
        image: tomqwu/voter-service-nginx:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: UPSTREAM_HOSTNAME
          value: localhost
      - name: mongodb-api
        image: mongo
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-apm-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: elastic-apm-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer