apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-user-service-demo
  labels:
    app: elastic-user-service-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-user-service-demo
  template:
    metadata:
      labels:
        app: elastic-user-service-demo
    spec:
      containers:
      - name: elastic-user-service-demo
        image: tomqwu/user-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "1"
        env:
        - name: SPRING_PROFILE
          value: poc
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_DATABASE
          value: "users"
        - name: MYSQL_USER
          value: "app"
        - name: MYSQL_PASSWORD
          value: "ecvbjkl9876t"
        - name: ELASTIC_APM_ACTIVE
          value: "true"
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          value: "com.example,org.example"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "service-user"
        - name: ELASTIC_APM_SERVER_URLS
          value: "https://apm-server-quickstart-apm-http:8200/"
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: "false"
        - name: ELASTIC_APM_SECRET_TOKEN
          value: "c92cq56gnjmkrr44vb566qwh"
      - name: mysql
        image: mysql:8
        imagePullPolicy: Always
        command: --default-authentication-plugin=mysql_native_password
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: qazxsw
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
          value: ecvbjkl9876t
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-user-service-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: elastic-user-service-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
