# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ## name of ConfigMap. This will be referred from volume definition
  name: mysql-config2
  labels:
    app: mysql
data:
  ## default_auth is the name of config. This will be referred from volume mount definition
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-user-service-demo2
  labels:
    app: elastic-user-service-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-user-service-demo2
  template:
    metadata:
      labels:
        app: elastic-user-service-demo2
    spec:
      containers:
      - name: user
        image: tomqwu/user-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "1"
        env:
        - name: SPRING_PROFILE
          value: poc
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_DATABASE
          value: "users"
        - name: MYSQL_USER
          value: "app"
        - name: MYSQL_PASSWORD
          value: "ecvbjkl9876t"
        - name: ELASTIC_APM_ACTIVE
          value: "true"
        - name: ELASTIC_APM_APPLICATION_PACKAGES
          value: "com.example,org.example"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "service-user2"
        - name: ELASTIC_APM_SERVER_URLS
          value: "https://apm-server-quickstart2-apm-http:8201/"
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: "false"
        - name: ELASTIC_APM_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: apm-server-quickstart2-apm-token
              key: secret-token
      - name: mysql
        image: mysql:8
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: qazxsw
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: app
        - name: MYSQL_PASSWORD
          value: ecvbjkl9876t
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-config-volume ## specify volume name
          mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
          subPath: default_auth
      volumes:
      - name: mysql-config-volume ## volume name
        configMap:
          name: mysql-config2
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-user-service-demo2
spec:
  selector:
    app: elastic-user-service-demo2
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: LoadBalancer
