apiVersion: apm.k8s.elastic.co/v1beta1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.4.0
  count: 1
  config:
    apm-server:
      secret_token: ''
      ssl:
        enabled: false
      rum:
        enabled: true
        allow_origins: ['*']

  elasticsearchRef:
    name: quickstart
