apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.4.1
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
        - port: 5601
          targetPort: 5601
  elasticsearchRef:
    name: quickstart
